mendersoftware/meta-mender-community

README.md
Leaving "stealth mode" on this repository :). Please let me know what you think about this.
=> README: document layer structure

meta-mender-intel/scripts/manifest-intel.xml, meta-mender-intel/templates/bblayers.conf.sample, meta-mender-intel/templates/local.conf.append, scripts/setup-environment
=> meta-mender-intel: initial template files for Minnowboard

meta-mender-atmel/README.md, meta-mender-atmel/conf/layer.conf, meta-mender-atmel/recipes-bsp/u-boot/files/0001-ARM-sama5d27_som1_ek-Add-support-to-mender.patch, meta-mender-atmel/recipes-bsp/u-boot/files/0002-Integration-of-Mender-boot-code-into-U-Boot.patch, meta-mender-atmel/recipes-bsp/u-boot/u-boot-at91_%.bbappend, meta-mender-atmel/recipes-bsp/u-boot/u-boot-mender-atmel.inc, meta-mender-atmel/scripts/manifest-atmel.xml, meta-mender-atmel/templates/bblayers.conf.sample, meta-mender-atmel/templates/local.conf.append, scripts/setup-environment
Add support for the following Atmel/Microchip Board:
- sama5d27-som1-ek-sd
Signed-off-by: Pierre-Jean Texier <pierre-jean.texier@lafon.fr>
=> integration: add Atmel sama5d27-som1-ek-sd

README.md
Recently there where some updates to the mender.io site and digital assets where moved. Update URL accordingly.
=> README: update Mender log URL

meta-mender-up/scripts/manifest-up.xml, meta-mender-up/templates/bblayers.conf.sample, meta-mender-up/templates/local.conf.append, scripts/setup-environment
https://up-board.org/upsquared/specifications/
=> add support for UP2 board

meta-mender-toradex-nxp/templates/local.conf.append
Depends on https://github.com/mendersoftware/meta-mender/pull/640
=> Add support for Colibri iMX7 eMMC variant

README.md
=> Add missing repo sync step to README.md

meta-mender-nxp/README.md, meta-mender-nxp/conf/layer.conf, meta-mender-nxp/recipes-bsp/u-boot-scr/files/imx7s-warp/boot.cmd, meta-mender-nxp/recipes-bsp/u-boot-scr/u-boot-scr.bb, meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/0002-Integration-of-Mender-boot-code-into-U-Boot.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/imx7d-pico/0001-Add-NXP-Pico-Pi-imx7d-board.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/imx7s-warp/0001-ARM-WaRP7-Add-support-to-mender.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc_%.bbappend, meta-mender-nxp/recipes-bsp/u-boot/u-boot-mender-nxp.inc, meta-mender-nxp/scripts/manifest-nxp.xml, meta-mender-nxp/templates/bblayers.conf.sample, meta-mender-nxp/templates/local.conf.append, scripts/setup-environment
Add support for the following NXP Boards:
- WaRP7
- Pico-Pi
=> Add support for WaRP7 & Pico-Pi

meta-mender-toradex-nxp/conf/layer.conf, meta-mender-toradex-nxp/recipes-bsp/u-boot/files/0001-Set-default-display-resolution-to-800x480-WVGA.patch, meta-mender-toradex-nxp/recipes-bsp/u-boot/u-boot-toradex-fsl-fw-utils_%.bbappend, meta-mender-toradex-nxp/recipes-bsp/u-boot/u-boot-toradex-mender-community.inc, meta-mender-toradex-nxp/recipes-bsp/u-boot/u-boot-toradex_%.bbappend, meta-mender-toradex-nxp/recipes-kernel/linux/files/0001-Fix-capacitive-touch-for-7inch-display-with-Aster-ca.patch, meta-mender-toradex-nxp/recipes-kernel/linux/linux-toradex_4.9-1.0.x.bbappend
This is to address https://tracker.mender.io/browse/MEN-2057
=> Setup display resolution and touch panel on Colibri i.MX7

templates/local.conf.append
(cherry picked from commit 8b854410dfe91d128e71a51fab42adbbeacb3666)
=> add additional Mender server config examples in templates

meta-mender-raspberrypi/scripts/manifest-raspberrypi.xml, meta-mender-raspberrypi/templates/local.conf.append, scripts/mender.xml
Includes the initial update to mender.xml.
=> Raspberry Pi Thud update

meta-mender-rockchip/scripts/manifest-rockchip.xml
Missed updating the manifest file in https://github.com/mendersoftware/meta-mender-community/pull/32
=> Thud tinker v2

meta-mender-intel/scripts/manifest-intel.xml
=> Thud for Minnowboard

meta-mender-beaglebone/scripts/manifest-beaglebone.xml
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
=> Bump BBB to thud

meta-mender-atmel/README.md, meta-mender-atmel/conf/layer.conf, meta-mender-atmel/scripts/manifest-atmel.xml, meta-mender-atmel/templates/local.conf.append
=> meta-atmel: update to thud release

meta-mender-atmel/README.md
=> atmel/README : Fix typo

meta-mender-clearfog/conf/layer.conf, meta-mender-clearfog/recipes-bsp/clearfog-u-boot-scr/clearfog-u-boot-scr.bbappend, meta-mender-clearfog/recipes-bsp/clearfog-u-boot-scr/files/boot.cmd.in, meta-mender-clearfog/recipes-bsp/u-boot/patches/0001-Integration-of-Mender-boot-code-into-U-Boot.patch, meta-mender-clearfog/recipes-bsp/u-boot/patches/0001-configs-clearfog-Mender-integration.patch, meta-mender-clearfog/recipes-bsp/u-boot/u-boot-solidrun-a38x-fw-utils_%.bbappend, meta-mender-clearfog/recipes-bsp/u-boot/u-boot-solidrun-a38x-mender.inc, meta-mender-clearfog/recipes-bsp/u-boot/u-boot-solidrun-a38x_%.bbappend, meta-mender-clearfog/scripts/manifest-clearfog.xml, meta-mender-clearfog/templates/bblayers.conf.sample, meta-mender-clearfog/templates/local.conf.append, scripts/setup-environment
I seem to have created the [Mender Hub post](https://hub.mender.io/t/solidrun-clearfog-base/370) but forgot to create a PR :)
=> add support for SolidRun ClearFog Base board

meta-mender-nxp/README.md, meta-mender-nxp/recipes-bsp/u-boot/u-boot-boundary/0001-ARM-nitrogen8m-Add-support-to-mender.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-boundary_%.bbappend, meta-mender-nxp/recipes-bsp/u-boot/u-boot-script-boundary/0001-bootscript-add-Mender-support.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-script-boundary_%.bbappend, meta-mender-nxp/scripts/manifest-nxp.xml, meta-mender-nxp/templates/bblayers.conf.sample, meta-mender-nxp/templates/local.conf.append
https://boundarydevices.com/product/nitrogen8m/
=> mender-nxp: add support for Nitrogen8m from Boundary Devices

meta-mender-qemu/scripts/manifest-qemu.xml
=> qemu: update default revision in manifest file to match mender.xml

meta-mender-qemu/scripts/manifest-qemu.xml
=> qemu: update poky revision to thud

meta-mender-nxp/README.md, meta-mender-nxp/conf/layer.conf, meta-mender-nxp/recipes-bsp/u-boot/files/0001-tools-fix-cross-compiling-tools-when-HOSTCC-is-overr.patch, meta-mender-nxp/recipes-bsp/u-boot/files/fw_env.config, meta-mender-nxp/recipes-bsp/u-boot/u-boot-edm-fw-utils_2017.03.bb, meta-mender-nxp/recipes-bsp/u-boot/u-boot-edm_%.bbappend, meta-mender-nxp/recipes-bsp/u-boot/u-boot-mender-edm.inc, meta-mender-nxp/templates/bblayers.conf.append, meta-mender-nxp/templates/local.conf.append
=> Initial support for pico i.MX7 on rocko

meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
=> update-modules: fetch sources from mendersoftware organization on github

meta-mender-imx/conf/layer.conf, meta-mender-imx/recipes-bsp/u-boot/u-boot-imx/imx8mqevk/0001-Add-Mender-support.patch, meta-mender-imx/recipes-bsp/u-boot/u-boot-imx/imx8mqevk/0002-Improve-boot-startup-time.patch, meta-mender-imx/recipes-bsp/u-boot/u-boot-imx_%.bbappend, meta-mender-imx/recipes-bsp/u-boot/u-boot-mender-imx.inc, meta-mender-imx/scripts/fsl-setup-mender.sh, meta-mender-imx/scripts/imx-4.14.98-2.0.0_demo_mender.xml, meta-mender-imx/templates/local.conf.append
This largely based on previous work by @thochstein, with some minor changes/cleanups to better align with the structure in meta-mender-community.
=> initial integration for imx8mqevk board using the i.MX BSP

meta-mender-96boards/README.md, meta-mender-96boards/conf/layer.conf, meta-mender-96boards/recipes-bsp/l-loader/l-loader-poplar_%.bbappend, meta-mender-96boards/recipes-bsp/u-boot/patches/0001-configs-poplar-integrate-Mender.patch, meta-mender-96boards/recipes-bsp/u-boot/u-boot-poplar.bbappend, meta-mender-96boards/recipes-mender/mender/files/mender-device-identity, meta-mender-96boards/recipes-mender/mender/mender_%.bbappend, meta-mender-96boards/scripts/manifest-96boards.xml, meta-mender-96boards/scripts/setup-environment-mender.sh, meta-mender-96boards/templates/local.conf.append
https://www.96boards.org/product/poplar/
=> add support for Poplar from 96Boards

README.md
=> README: update branch revision

templates/local.conf.append
=> mender: Add commented values for storage configuration.

meta-mender-atmel/recipes-bsp/u-boot/files/0001-ARM-sama5d27_som1_ek-Add-support-to-mender-for-U-Boo.patch
=> U-Boot: refresh patches for linux4sam_6.1

meta-mender-clearfog/recipes-bsp/clearfog-u-boot-scr/files/boot.cmd.in, meta-mender-clearfog/templates/local.conf.append
This layer depends upon pull request: [https://github.com/mirzak/meta-clearfog/pull/3](https://github.com/mirzak/meta-clearfog/pull/3)
Adds support for the clearfog-pro, main change compared to the clearfog branch is support for the 6 port switch.
=> Add clearfog-pro support.

meta-mender-beaglebone/conf/layer.conf, meta-mender-beaglebone/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_%.bbappend, meta-mender-beaglebone/recipes-bsp/u-boot/u-boot-mender-beaglebone.inc, meta-mender-beaglebone/recipes-bsp/u-boot/u-boot_%.bbappend, meta-mender-beaglebone/templates/bblayers.conf.sample
=> Add support for Beaglebone Black

meta-mender-update-modules/recipes-mender/mender-update-modules/mender-ipk_git.bb, meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
=> mender-ipk: Initial commit of recipe for IPK-based package updates

meta-mender-nxp/README.md, meta-mender-nxp/conf/layer.conf, meta-mender-nxp/recipes-bsp/u-boot-scr/files/imx7d-pico/boot.cmd, meta-mender-nxp/recipes-bsp/u-boot-scr/u-boot-scr.bb, meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/imx7d-pico/0001-ARM-Pico-Pi-i.MX7D-support-to-mender.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/imx7s-warp/0001-ARM-WaRP7-Add-support-to-mender.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc_%.bbappend, meta-mender-nxp/recipes-bsp/u-boot/u-boot-mender-nxp.inc, meta-mender-nxp/recipes-kernel/linux/linux-fslc/imx7d-pico/0001-linux-fslc-imx7d-pico-Disable-panel.patch, meta-mender-nxp/recipes-kernel/linux/linux-fslc_%.bbappend, meta-mender-nxp/scripts/manifest-nxp.xml, meta-mender-nxp/templates/local.conf.append
4c3f561 mender-nxp: linux: Disable panel
a45c117 meta-mender-nxp: update to warrior release
=> mender-nxp: bump to warrior

meta-mender-odroid/scripts/manifest-odroid.xml
=> odroid: update default.xml manifest to warrior branch

meta-mender-nxp/README.md, meta-mender-nxp/recipes-bsp/u-boot-scr/files/imx7dsabresd/boot.cmd, meta-mender-nxp/recipes-bsp/u-boot-scr/u-boot-scr.bb, meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/imx7dsabresd/0001-mx7dsabresd-Add-support-to-mender.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-mender-nxp.inc, meta-mender-nxp/templates/local.conf.append
https://www.nxp.com/design/development-boards/i.mx-evaluation-and-development-boards/sabre-board-for-smart-devices-based-on-the-i.mx-7dual-applications-processors:MCIMX7SABRE
Signed-off-by: Joris Offouga <offougajoris@gmail.com>
=> meta-mender-nxp: Add i.MX7D Sabre

meta-mender-sunxi/README.md, meta-mender-sunxi/conf/layer.conf
Verified on orangepi zero board boots fine.
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
=> meta-mender-sunxi: Added warrior to LAYERSERIES_COMPAT

meta-mender-sunxi/scripts/manifest-sunxi.xml
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
=> manifest-sunxi; Bump to warrior branch

meta-mender-update-modules/recipes-mender/mender-update-modules/mender-rootfs-version-check_git.bb, meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
=> Add new rootfs update module with version checking capability.

meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
Not sure how but I put the sha of the tree object rather than the
commit object.
=> Add proper commit hash.

meta-mender-update-modules/recipes-mender/mender-update-modules/mender-rootfs-version-check_git.bb, meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
Needed on this branch for a customer project.
=> Rocko backports

meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
=> update-modules: Update SRCREV for bash function fix

meta-mender-coral/README.md, meta-mender-coral/conf/layer.conf, meta-mender-coral/recipes-bsp/coral-boot-script/cora-boot-script.bbappend, meta-mender-coral/recipes-bsp/coral-boot-script/files/boot.txt, meta-mender-coral/recipes-bsp/u-boot/patches/0001-imx8mq_phanbell-add-Mender-requirements.patch, meta-mender-coral/recipes-bsp/u-boot/patches/0002-U-Boot-pre-2017.03-integration-of-Mender-boot-code-i.patch, meta-mender-coral/recipes-bsp/u-boot/patches/0003-default-gcc.patch, meta-mender-coral/recipes-bsp/u-boot/u-boot-coral_%.bbappend, meta-mender-coral/scripts/manifest-coral.xml, meta-mender-coral/templates/bblayers.conf.sample, meta-mender-coral/templates/local.conf.append, scripts/setup-environment
=> initial support for Google Coral Dev Board

meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
=> Update srcrev for upstream fix; path to version-compare script

meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
=> Update srcrev for upstream fix; path to version-compare script... again

.github/stale.yml
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
=> Added a configuration file for stalebot

meta-mender-variscite/README.md
=> Readme update for supported boards.

meta-mender-variscite/README.md
=> Add DART-MX8M to README.

meta-mender-coral/recipes-bsp/u-boot/patches/0001-imx8mq_phanbell-add-Mender-requirements.patch
=> coral: add missing CONFIG_SYS_REDUNDAND_ENVIRONMENT

meta-mender-sunxi/README.md, meta-mender-sunxi/conf/layer.conf, meta-mender-sunxi/scripts/manifest-sunxi.xml, scripts/mender-no-setup.xml, scripts/mender.xml
As sunxi was updated to zeus recently bump to dunfell is pretty easy ;). tested on orange-pi-pc-plus and orange-pi-zero
=> Sunxi dunfell updates

meta-mender-nxp/README.md, meta-mender-nxp/recipes-bsp/u-boot/u-boot-boundary/0001-ARM-nitrogen8m-Add-support-to-mender.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-boundary/0001-Mender-Add-support-for-KOE-tx31d200vm0baa-display.patch, meta-mender-nxp/recipes-bsp/u-boot/u-boot-boundary_%.bbappend, meta-mender-nxp/recipes-bsp/u-boot/u-boot-script-boundary/0001-bootscript-add-Mender-support.patch, meta-mender-nxp/scripts/manifest-nxp.xml
Some changes needed for the current warrior branch on the nitrogen8m platform.
This goes with https://github.com/boundarydevices/meta-boundary/pull/12
@texierp can you take a look?
=> Warrior nitrogen8m

meta-mender-qemu/README.md, meta-mender-qemu/scripts/manifest-qemu.xml
This is the first commit from #169 , built, and tested locally, and confirmed that it works.
=> Bump: manifest-qemu poky revision to Dunfell

meta-mender-raspberrypi/README.md, meta-mender-raspberrypi/scripts/manifest-raspberrypi.xml
=> Bump meta-mender-raspberrypi to dunfell

meta-mender-tn-imx-bsp/README.md, meta-mender-tn-imx-bsp/conf/layer.conf, meta-mender-tn-imx-bsp/recipes-bsp/u-boot/u-boot-tn-imx/pico-imx8mm/0001-configs-pico-imx8mm-add-Mender-support.patch, meta-mender-tn-imx-bsp/recipes-bsp/u-boot/u-boot-tn-imx_%.bbappend, meta-mender-tn-imx-bsp/recipes-bsp/u-boot/u-boot-tools_%.bbappend, meta-mender-tn-imx-bsp/scripts/imx-5.4.24-2.1.0_demo_mender.xml, meta-mender-tn-imx-bsp/scripts/tn-setup-mender.sh, meta-mender-tn-imx-bsp/templates/local.conf.append
I have been thinking about if I should merge this together with `meta-mender-imx`, but in the end decided not to. Mostly because we will add a couple of more boards here soon and wanted to see how that turns out first, and could follow up with a consolidation.
=> initial support for TechNexion BSP layer

meta-mender-qemu/scripts/manifest-qemu.xml, meta-mender-qemu/templates/bblayers.conf.sample
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>
=> Adding meta-openembedded/meta-oe as it is needed now.

meta-mender-tn-imx-bsp/templates/local.conf.append
Signed-off-by: Mirza Krak <mirza@maneoz.tech>
=> tn-imx-bsp: change default boot media to eMMC

meta-mender-imx/README.md, meta-mender-imx/conf/layer.conf, meta-mender-imx/recipes-bsp/u-boot/u-boot-imx_%.bbappend, meta-mender-imx/scripts/fsl-setup-mender.sh, meta-mender-imx/scripts/imx-4.19.35-1.1.2_demo_mender.xml, meta-mender-imx/templates/local.conf.append
Added support for NXP's **i.MX 6UL Evaluation Kit**
*NOTE*: It still points to my forked repo for initialization scripts. After merge I'll update those links to meta-mender-community
Signed-off-by: Daniel Selvan D <danilselvan@gmail.com>
=> Added meta-mender-imx

meta-mender-imx/README.md, meta-mender-imx/classes/mender-setup-imx.bbclass, meta-mender-imx/conf/layer.conf, meta-mender-imx/recipes-bsp/grub-mender-grubenv/files/imx8mnevk/02_console_grub.cfg, meta-mender-imx/recipes-bsp/grub-mender-grubenv/grub-mender-grubenv_%.bbappend, meta-mender-imx/recipes-bsp/grub/grub-efi-mender-precompiled_%.bbappend, meta-mender-imx/recipes-bsp/grub/grub-efi_%.bbappend, meta-mender-imx/recipes-bsp/u-boot-imx/files/imx8mnevk/0001-Switch-to-CONFIG_DISTRO_DEFAULTS-for-bootcmd.patch, meta-mender-imx/recipes-bsp/u-boot-imx/u-boot-imx_%.bbappend, meta-mender-imx/recipes-bsp/u-boot-imx/u-boot-tools_%.bbappend, meta-mender-imx/scripts/imx-5.4.3-2.0.0_demo_mender.xml, meta-mender-imx/scripts/imx-setup-mender.sh, meta-mender-imx/templates/local.conf.append, meta-mender-nxp/conf/layer.conf
Zeus Mender integration for imx8mnevk
This currently requires using [my fork of imx-manifest.](https://github.com/drewmoseley/imx-manifest/tree/wip-zeus)
=> Zeus Mender integration for imx8mnevk

meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass
This appears to have been left in by accident.
=> Remove hard-coded debug message

meta-mender-beaglebone/README.md, meta-mender-beaglebone/conf/layer.conf, meta-mender-beaglebone/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_%.bbappend, meta-mender-beaglebone/recipes-bsp/u-boot/u-boot-mender-beaglebone.inc, meta-mender-beaglebone/recipes-bsp/u-boot/u-boot_%.bbappend, meta-mender-beaglebone/scripts/manifest-beaglebone.xml
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
=> Bump bbb branch to dunfell

README.md
Signed-off-by: Alan Martinovic <alan.martinovic@northern.tech>
=> List community maintainers on a github wiki page

meta-mender-atmel/README.md, meta-mender-nxp/README.md
Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>
=> layer: update email address for Pierre-Jean Texier

meta-mender-toradex-nxp/templates/local.conf.append.colibri-imx6ull
=> Remove artifact name for imx6ull

meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
See discussion/approval in https://github.com/OE4T/meta-mender-community/pull/13
Signed-off-by: Niels Avonds <niels@nobi.life>
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>
=> Create /run/tegra-nv-bootctrl when updating using uboot as well

meta-mender-raspberrypi/templates/local.conf.append
See https://github.com/agherzan/meta-raspberrypi/blob/master/docs/extra-build-config.md#enable-uart
=> meta-mender-raspberrypi: Enable UART

README.md
Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>
=> README: bump to dunfell release

meta-mender-toradex-nxp/b2qt-distro/recipes-bsp/u-boot/u-boot-toradex/0002-apalis-imx6-test-for-Capacitive-Touch-Display-7-Para-with-mender.patch, meta-mender-toradex-nxp/b2qt-distro/recipes-bsp/u-boot/u-boot-toradex_2019%.bbappend, meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass, meta-mender-toradex-nxp/conf/layer.conf, meta-mender-toradex-nxp/recipes-bsp/u-boot/u-boot-toradex_%.bbappend
I've been working on a project with apalis-imx6 on Zeus and needed these changes.  I will also look to see what of these need to move forward to dunfell.
=> A few changes needed for current zeus builds

meta-mender-toradex-nxp/recipes-bsp/u-boot/files/apalis-imx8/0001-configs-toradex-board-specific-mender-integration.patch, meta-mender-toradex-nxp/templates/local.conf.append
Fix mender integration patch for Toradex Apalis IMX8, add board-specific mender defines
=> Toradex Apalis IMX8 integration

.gitlab-ci.yml
So that the pipelines report back to the Pull Requests in GitHub...
=> pipeline: Add GitHub status updates

meta-mender-tn-imx-bsp/README.md, meta-mender-tn-imx-bsp/recipes-bsp/u-boot/u-boot-tn-imx/edm-g-imx8mp/0001-configs-edm-g-imx8mp-add-Mender-support.patch, meta-mender-tn-imx-bsp/recipes-bsp/u-boot/u-boot-tn-imx_%.bbappend
This patch is based on pico-imx8mm
Passed tests:
1. build
2. boot
3. connect to hosted.mender.io
4. firmware upgrade
=> Add edg-g-imx8mp by TechNexion

meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass, meta-mender-toradex-nxp/templates/local.conf.append
Just a few minor things for Toradex builds on Dunfell.
=> Dunfell updates for Toradex

meta-mender-toradex-nxp/README.md, scripts/mender-no-setup-layers.xml, scripts/mender-no-setup.xml, scripts/mender.xml
=> fix: mender.xml: bump missed revision dunfell

meta-mender-st-stm32mp/README.md
=> chore: update stm32 readme for kirkstone release

meta-mender-beaglebone/README.md, meta-mender-beaglebone/scripts/manifest-beaglebone.xml
Ticket: None
Changelog: update Beaglebone Black repo manifest to kirkstone
=> chore: bump docs and manifest of beaglebone to kirkstone

meta-mender-update-modules/classes/sanity-meta-mender-update-modules.bbclass, meta-mender-update-modules/conf/layer.conf
=> update-modules: Remove sanity check for override syntax.

meta-mender-qemu/README.md, meta-mender-qemu/scripts/manifest-qemu.xml
=> meta-mender-qemu: bump to kirkstone release

meta-mender-raspberrypi/README.md, meta-mender-raspberrypi/scripts/manifest-raspberrypi.xml
=> meta-mender-raspberrypi: bump to kirkstone release

meta-mender-atmel/README.md, meta-mender-atmel/classes/sanity-meta-mender-atmel.bbclass, meta-mender-atmel/conf/layer.conf, meta-mender-atmel/scripts/manifest-atmel.xml
=> meta-mender-atmel: bump to kirkstone release

meta-mender-sunxi/classes/sanity-meta-mender-sunxi.bbclass, meta-mender-sunxi/conf/layer.conf
Changelog: title
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>
=> meta-mender-sunxi: Remove sanity check

meta-mender-nxp/README.md
=> README: use stable branch for kirkstone

README.md
Replace Dunfell with Kirkstone in the download command.
=> README.md: Replace Dunfell with Kirkstone

meta-mender-toradex-nxp/recipes-bsp/u-boot-distro-boot/files/toradex-bsp-5.7.2/0001-Adapt-boot.cmd.in-to-Mender.patch, meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.7.2
This adds support for the latest point release of the Toradex BSP.
=> toradex: Add support for BSP 5.7.2.

meta-mender-update-modules/README.md
=> meta-mender-update-modules: fix logo in Readme

meta-mender-toradex-nxp/README.md
Enhanced and updated QuickStart
=> Update README.md of meta-mender-toradex-nxp

.github/workflows/build.yml
Ticket: None
(cherry picked from commit ef58a164d883d2cb325daec680f30629c19e915b)
=> chore: bump github action checkout to v4
