- meta-mender-toradex-nxp/scripts/manifest-toradex.xml
- meta-mender-toradex-nxp/templates/bblayers.conf.sample
- meta-mender-toradex-nxp/templates/local.conf.append
- scripts/setup-environment
Toradex does not use 'poky' in upstream configuration, and instead
provide a distrobution based on Angstrom + oe-core. To simplify
the setup a bit the template files here are based on poky and more
aligned with the rest of boards and provides a good enough base
to evaluate Mender on Toradex NXP SoMs.
> meta-mender-toradex-nxp: initial template files

- README.md
Recently there where some updates to the mender.io
site and digital assets where moved. Update URL accordingly.
(cherry picked from commit 03d97eb3e1df1912420374e28f1d046c17d1b622)
> README: update Mender logo URL

- meta-mender-tegra/README.md
- meta-mender-tegra/classes/image_types_mender_tegra.bbclass
- meta-mender-tegra/conf/layer.conf
- meta-mender-tegra/recipes-bsp/tegra-binaries/files/flash_l4t_t186.custom.xml
- meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-binaries_%.bbappend
- meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-bootfiles_%.bbappend
- meta-mender-tegra/recipes-bsp/u-boot/patches/0001-env-tool-add-command-line-option-to-input-lockfile-p.patch
- meta-mender-tegra/recipes-bsp/u-boot/patches/0003-tegra-Integration-of-Mender-boot-code-into-U-Boot.patch
- meta-mender-tegra/recipes-bsp/u-boot/patches/0010-tegra-mender-auto-configured-modified.patch
- meta-mender-tegra/recipes-bsp/u-boot/patches/0011-Jetson-TX2-mender-boot-commands.patch
- meta-mender-tegra/recipes-bsp/u-boot/patches/0012-Update-environment-defaults-for-tegra.patch
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-fw-utils-tegra_%.bbappend
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-mender-tegra.inc
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
- meta-mender-tegra/recipes-core/images/tegra186-minimal-initramfs.bbappend
- meta-mender-tegra/scripts/deploy.sh
- meta-mender-tegra/scripts/manifest-tegra.xml
- meta-mender-tegra/templates/bblayers.conf.sample
- meta-mender-tegra/templates/local.conf.append
- scripts/setup-environment
Thanks for creating this project!
This pull request adds support for NVIDIA tegra, as discussed [in the forum](https://groups.google.com/a/lists.mender.io/forum/#!topic/mender/ISaA1ll9Fbo) and [mender hub page](https://hub.mender.io/t/nvidia-tegra-jetson-tx2/123).
To test before the pull request is complete you can use
```
repo init \
-u https://github.com/Trellis-Logic/meta-mender-community \
-m meta-mender-tegra/scripts/manifest-tegra.xml \
-b add-tegra
repo sync
```
Based on Mirza's recommendations in the forum and the recommendations in the [meta-tegra pull request](https://github.com/madisongh/meta-tegra/pull/114) I haven't tried to update partitioning or moving u-boot environment out of a dedicated sector.  Although I'd expect these patches to support any NVIDIA platforms supported …
> Add NVIDIA tegra support

- meta-mender-sunxi/recipes-kernel/linux/linux-mainline_%.bbappend
Few patches which add wifi support, but one blocking point (kernel doesn't boot without this change: https://github.com/linux-sunxi/meta-sunxi/issues/232)
> Added support for orangepi zero

- meta-mender-nxp/templates/local.conf.append
With the update of the linux-fslc the block memory and the emmc has changed
Signed-off-by: Joris Offouga <offougajoris@gmail.com>
> Fix storage device for Pico-Pi i.MX7D

- meta-mender-odroid/classes/odroid-sdimg.bbclass
- meta-mender-odroid/conf/layer.conf
- meta-mender-odroid/recipes-bsp/odroid-u-boot-scr/files/boot.cmd.in
- meta-mender-odroid/recipes-bsp/odroid-u-boot-scr/odroid-u-boot-scr.bb
- meta-mender-odroid/recipes-bsp/u-boot/patches/odroid-c2/0001-configs-meson-gx-add-Mender-requirements.patch
- meta-mender-odroid/recipes-bsp/u-boot/u-boot_%.bbappend
- meta-mender-odroid/recipes-kernel/linux/linux-stable/vfat.cfg
- meta-mender-odroid/recipes-kernel/linux/linux-stable_%.bbappend
- meta-mender-odroid/scripts/manifest-odroid.xml
- meta-mender-odroid/templates/bblayers.conf.sample
- meta-mender-odroid/templates/local.conf.append
- scripts/setup-environment
The integration is based on the "odroid-c2" machine which uses upstream Linux
and U-boot.
This integration probably will not work out-of-the-box for the "odroid-c2-hardkernel"
machine which uses "hardkernel" U-boot and Linux forks.
> initial support for Odroid C2 SBC

- meta-mender-imx/classes/mender-setup-imx.bbclass
- meta-mender-imx/templates/local.conf.append
Having the definition in a IMAGE_CLASS will make these only applicable
on the image built, but this is not applied when you build e.g u-boot
which also needs a correct definition of MENDER_STORAGE_DEVICE.
> imx: move MENDER_STORAGE_DEVICE definitions to local.conf.bbappend

- meta-mender-nxp/scripts/manifest-nxp.xml
Fixes:
Trying to boot from MMC1
No matching DT out of these options:
Configuration to load ATF before U-Boot
No matching DT out of these options:
Configuration to load ATF before U-Boot
mmc_load_image_raw_sector: mmc block read error
SPL: failed to boot from all boot devices
> nxp/nitrogen8m: use a specific revision for meta-boundary

- meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
This includes the following changes:
7631f32 dir-overlay: fail if update module is not executed by a superuser
dda8192 dir-overlay: preserve file/directory ownership and mode permissions
3176c72 module/dir-overlay: fix bashism in rollback state
> update-modules: bump git srcrev

- meta-mender-clearfog/templates/local.conf.append
Missed the $ sign in the ```local.conf.append``` file.
A little surprised since I compiled it prior to saying it's ready, must have had a stale build at the time.
Anyway a quick fix.
> clearfog: fix missing $ in local.append template

- meta-mender-beaglebone/conf/layer.conf
- meta-mender-beaglebone/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_%.bbappend
- meta-mender-beaglebone/recipes-bsp/u-boot/u-boot-mender-beaglebone.inc
- meta-mender-beaglebone/recipes-bsp/u-boot/u-boot_%.bbappend
- meta-mender-beaglebone/scripts/manifest-beaglebone.xml
- meta-mender-beaglebone/templates/bblayers.conf.sample
- meta-mender-beaglebone/templates/local.conf.append
This sets up mender_pre_setup_commands to use the findfdt environment variable to setup mender_dtb_name.
> Beaglebone

- README.md
When zsh is default shell it wants to know path of file being sourced
Changelog: Commit
> README.md: update setup example for zsh

- meta-mender-raspberrypi/README.md
Per our discussion in #101, @texierp @drewmoseley , here is a suggested template for sub-layers and the information that they should contain (including maintainer)
> raspberrypi: add README containing maintainer information

- meta-mender-tegra/recipes-bsp/mender-tegra-bup-payload-install/mender-tegra-bup-payload-install_1.0.bb
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
To match [logic change](https://github.com/madisongh/meta-tegra/issues/204) in meta-tegra we now need to use the u-boot-bup-payload class to generate bup payloads.
Move logic into a new mender-tegra-bup-payload-install class
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>
> meta-mender-tegra: Add u-boot-bup-payload support

- meta-mender-tegra/README.md
- meta-mender-tegra/classes/image_types_mender_tegra.bbclass
- meta-mender-tegra/classes/tegra-mender-setup.bbclass
- meta-mender-tegra/recipes-bsp/u-boot/patches/0010-tegra-mender-auto-configured-modified.patch
- meta-mender-tegra/recipes-bsp/u-boot/patches/0013-Jetson-Nano-mender-environment-in-mmc.patch
- meta-mender-tegra/recipes-bsp/u-boot/sdcard-layout-mender.in
- meta-mender-tegra/recipes-bsp/u-boot/sdcard-layout_%.bbappend
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-mender-tegra.inc
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
Jetson-nano development kit has a SD-card slot and no emmc. It does not support
nvidia redundant boot feature and therefore there is no dependency to the BUP Payload which
is used on jetson-tx2. Nvidia released a production module of the jetson-nano with 16GB emmc,
but this is not supported by this branch.
Even though there is no emmc, the sd-card is referenced as mmc device in u-boot, which is
why we use ENVIRONMENT_IS_IN_MMC.
Signed-off-by: Moritz Marquardt <moritz.marquardt@zeiss.com>
Signed-off-by: Etienne Cordonnier <etienne.cordonnier@taurob.com>
> meta-mender-tegra: add support for jetson-nano development kit

- meta-mender-tegra/classes/tegra-mender-setup.bbclass
See https://github.com/Trellis-Logic/meta-mender-community/pull/8 and [related mender hub question](https://hub.mender.io/t/nvidia-tegra-jetson-tx2/123/27)
Fixes support for core-image-minimal and any other images which use a non-zero value for IMAGE_ROOTFS_EXTRA_SPACE
> meta-mender-tegra: Fix image size calculation

- meta-mender-imx/recipes-bsp/u-boot/u-boot-imx/imx8mmevk/0003-Allow-Mender-to-live-in-eMMC.patch
- meta-mender-imx/recipes-bsp/u-boot/u-boot-imx/imx8mqevk/0003-Allow-Mender-to-live-in-eMMC.patch
- meta-mender-imx/recipes-bsp/u-boot/u-boot-imx_%.bbappend
- meta-mender-imx/templates/local.conf.append
Allow imx8mmevk/imx8mqevk to boot from eMMC through MENDER_UBOOT_STORAGE_DEVICE
variable. The default remains SD card for backward compatibility.
Signed-off-by: Tom Kuparowitz <tomas.kuparowitz@invasys.com>
> imx8mmevk/imx8mqevk: Fix boot from eMMC

- meta-mender-st-stm32mp/templates/local.conf.append
Found this when doing a clean build. Will merge as the board integration has been published on MH
> stm32mp: disable FLASHLAYOUT_CONFIG

- meta-mender-tegra/README.md
- meta-mender-tegra/classes/image_types_mender_tegra.bbclass
- meta-mender-tegra/classes/tegra-mender-setup.bbclass
- meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-bootfiles_%.bbappend
- meta-mender-tegra/recipes-bsp/u-boot/patches/0001-Move-jetson-nano-env-to-SDcard.patch
- meta-mender-tegra/recipes-bsp/u-boot/patches/0014-Handle-pre-v2020-u-boot-env-redundancy-for-tegra-pla.patch
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-mender-tegra.inc
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
- meta-mender-tegra/scripts/manifest-tegra.xml
These patches didn't make it into the original PR at https://github.com/mendersoftware/meta-mender-community/pull/147/commits.
Resolves errors with latest meta-tegra zeus branch and `signing images failed` errors from tegraparser.
See discussion in [this comment](https://hub.mender.io/t/jetson-tx2-updating-device-tree/2124/18) on mender hub.
> tegra zeus-test patches

- meta-mender-raspberrypi/templates/local.conf.append
Raspberry Pi devices should use the default (8MB).
> raspberrypi: remove custom partition alignment

- README.md
The current content is very outdated. The only branch that has up to date content is the "sumo" branch, this used to be the repository default branch, but as I have updated the default branch to `zeus` it makes sense to bring this up to date as well.
> README: update 'Connect with us' section

- meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-reboot-state-script
Mount old and new filesystem as read-only to avoid breaking delta-updates
Signed-off-by: Niels Avonds <niels@nobi.life>
> meta-mender-tegra: Fix delta updates

- meta-mender-tegra/README.md
- meta-mender-tegra/scripts/deploy.sh
Reference tegra-demo-distro deployment scheme for dunfell and
later builds.
Update deploy.sh to default to tegra-demo-distro deployment and
use tar.gz file.
> Update documentation and scripts for dunfell

- meta-mender-variscite/recipes-bsp/u-boot/u-boot-variscite.bbappend
- meta-mender-variscite/templates/local.conf.append
Since we use UEFI/GRUB integration on the Zeus branch, we don't need
u-boot-mender.inc.
> u-boot-variscite: Remove unneeded configurations.

- meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-nano-qspi-sd/flash_mender.xml
- meta-mender-tegra/recipes-bsp/u-boot/patches/0013-Reduce-env-size-on-p3450-0000-to-64KiB.patch
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-mender-tegra-vars.inc
- meta-mender-tegra/recipes-bsp/u-boot/u-boot-mender-tegra.inc
Per discussion at https://github.com/OE4T/meta-mender-community/pull/5
As of r32.3.1 (or possibly earlier) NVIDIA has defined a UBENV partition at offset 0x3D8000 for `jetson-nano-qspi-sd` partition layout, which is the layout used for the Nano development board with SD card.  Previously this area was defined as a `PAD` partition and we had stored our uboot environment in that location.  However, we'd also accidentally overflowed into the `VER_b` location with our definition of uboot storage environment from 0x3B0000 to 0x3F0000.  This might be a problem if/when we add support for [Nano redundant boot](https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/bootloader_update_nano_tx1.html) for bootloader components.
The area defined by …
> meta-mender-tegra: dunfell nano development board partition layout fixes

- meta-mender-imx/recipes-bsp/u-boot-imx/u-boot-imx_%.bbappend
Hi @drewmoseley ,
I'm really new on Mender architecture.
I tried to add a new board using meta-mender-imx layer for testing and I got this the following error:
"do_mender_tar_src" is missing.
it looks like the u-boot-imx_% is missing u-boot-mender.inc
Could you review it, thanks for your help :)
> imx: fix missing "do_mender_tar_src" task

- meta-mender-imx/recipes-bsp/u-boot-imx/u-boot-imx_%.bbappend
When switching to mender_feature_is_enabled function the include path was wrong.
As we have an include and not a require this doesn't trig any error.
Fix this by giving the correct include path to u-boot-mender.inc
Signed-off-by: Clément Péron <peron.clem@gmail.com>
> imx: Fix include path to u-boot-mender.inc

- scripts/mender-no-setup.xml
These are provided by upstream manifests.
> scripts: mender-no-setup: remove defaults

- scripts/mender-no-setup-layers.xml
THis manifest clones Mender layers to layers/ sub-directory, which
is used by some BSP's, e.g Toradex.
> scritps: add mender-no-setup-layers.xml

- meta-mender-toradex-nxp/templates/local.conf.append
> toradex-nxp: use U-boot integration as default for Toradex Verdin iMX8MM

- meta-mender-variscite/recipes-bsp/u-boot/files/imx8mn-var-som/0001-Switch-to-CONFIG_DISTRO_DEFAULTS-for-bootcmd.patch
- meta-mender-variscite/recipes-bsp/u-boot/files/imx8mn-var-som/0002-Store-Env-in-eMMC.patch
- meta-mender-variscite/recipes-bsp/u-boot/u-boot-tools_%.bbappend
- meta-mender-variscite/recipes-bsp/u-boot/u-boot-variscite.bbappend
- meta-mender-variscite/templates/local-emmc.conf.append
- meta-mender-variscite/templates/local-sdcard.conf.append
- meta-mender-variscite/templates/local.conf.append
This fixes up the imx8mn-var-som machine so that it works with the 5.4.24 BSP from Variscite.
It also enabled mender-uboot integration in addition to the standard mender-grub integration.
> Bsp v5.4.24

- meta-mender-tegra/classes/tegra-mender-setup.bbclass
Made the `MENDER_DATA_PART_NUMBER` and `MENDER_ROOTFS_PART_A/B_NUMBER` into defaults so they can be overwritten
> MENDER_DATA_PART_NUMBER and MENDER_ROOTFS_PART_A/B_NUMBER

- meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass
SPL_BINARY is not always present, which is the case for verdin-imx8mm
> toradex-nxp: make SPL_BINARY optional in mender_tezi image

- meta-mender-toradex-nxp/templates/local.conf.append
It is treated as a string in image_type_mender_tezi, so
setting "0" does not disable it, and it should be empty.
Fixes bd849438920 ("toradex-nxp: disable OFFSET_SPL_PAYLOAD for verdin-imx8mm")
Signed-off-by: Mirza Krak <mirza@maneoz.tech>
> toradex-nxp: set OFFSET_SPL_PAYLOAD as empty string

- meta-mender-tegra/classes/tegra-mender-setup.bbclass
- meta-mender-tegra/recipes-bsp/u-boot/libubootenv-fake/fw_printenv
* Fix typos in tegra-mender-setup
* Update the libubootenv-fake implementation of fw_printenv to work with the separator probe checks in mender-client 2.4.1
> Tegra fixes for dunfell

- meta-mender-tn-imx-bsp/README.md
- meta-mender-tn-imx-bsp/conf/layer.conf
- meta-mender-tn-imx-bsp/recipes-bsp/u-boot/u-boot-edm/pico-imx8mq/0001-configs-pico-imx8mq-add-Mender-support.patch
- meta-mender-tn-imx-bsp/recipes-bsp/u-boot/u-boot-edm_2018.03.bbappend
- meta-mender-tn-imx-bsp/scripts/mender-technexion.xml
- meta-mender-tn-imx-bsp/scripts/tn-setup-mender.sh
- meta-mender-tn-imx-bsp/templates/local.conf.append
Based heavily on the meta-mender-tn-imx-bsp layer in zeus as of revision
4d0df63278a7 add support for the PICO-IMX8M platform.
Signed-off-by: Tom Rini <trini@konsulko.com>
> meta-mender-tn-imx-bsp: Add support for the PICO-IMX8M platform

- meta-mender-tegra/classes/tegra-mender-setup.bbclass
- meta-mender-tegra/recipes-bsp/cboot/cboot-t18x_%.bbappend
- meta-mender-tegra/recipes-bsp/cboot/cboot-t19x_%.bbappend
- meta-mender-tegra/recipes-bsp/tegra-binaries/redundant-boot-overrides/update-nvbootctrl.service.in
- meta-mender-tegra/recipes-bsp/tegra-binaries/redundant-boot-overrides_%.bbappend
- meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-nv-boot-control-config_%.bbappend
- meta-mender-tegra/recipes-bsp/tools/setup-nv-boot-control/target-mkdir.conf
- meta-mender-tegra/recipes-bsp/tools/setup-nv-boot-control_%.bbappend
- meta-mender-tegra/recipes-mender/mender-client/mender-client_%.bbappend
- meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script
- meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
- meta-mender-tegra/recipes-mender/tegra-state-scripts/tegra-state-scripts_%.bbappend
This PR replaces https://github.com/mendersoftware/meta-mender-community/pull/208 and incorporates changes from @madisongh in https://github.com/OE4T/tegra-demo-distro/pull/31 to support read only rootfs mounts on both uboot and cboot tegra configurations during mender update, including persistent machine-id across updates in cboot.
Mender delta updates have not been specifically tested on cboot or uboot configurations with this PR but should be supported.
> tegra: Use read only mounts for uboot and cboot builds

- meta-mender-toradex-nxp/README.md
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/colibri-imx6ull/0001-colibri-imx6ull-mender-manual-U-Boot-integration.patch
Variable fdtfile ends up with a wrong value when using a custom device tree file (set via KERNEL_DEVICETREE). 
mender_dtb_name variable is set correctly though. So setting fdtfile to mender_dtb_name value fixes the issue.
Also on the same go, update my email address.
> Honor mender dtb variable

- meta-mender-beaglebone/scripts/manifest-beaglebone.xml
- meta-mender-beaglebone/templates/bblayers.conf.sample
This is the requirement to build mender demo images which require `jq`.
> Add meta openembedded to beaglebone

- meta-mender-update-modules/recipes-mender/mender-update-modules/mender-update-modules.inc
This includes the following changes:
54d3ed0 Merge pull request #19 from drewmoseley/master
8d65ecf dir-overlay: Ensure UID variable is set.
ed3db9c Merge pull request #18 from kacf/men-4044
19ec6a9 artifact-gen: Improve error message when mender-artifact is not found.
703610b Merge pull request #17 from merlin-northern/reboot_update_module
0ca31c7 Reboot update module
3070b3a Merge pull request #16 from tranchitella/k8s-update-module
947f625 k8s update module
34d87c3 Merge pull request #15 from mendersoftware/github_status_updates
016e379 Enable Github status updates from mendertesting repository.
Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>
> mender-update-modules: update to current HEAD

- meta-mender-atmel/README.md
- meta-mender-beaglebone/README.md
- meta-mender-coral/README.md
- meta-mender-intel/README.md
- meta-mender-nxp/README.md
- meta-mender-odroid/README.md
- meta-mender-qemu/README.md
- meta-mender-raspberrypi/README.md
- meta-mender-sunxi/README.md
- meta-mender-tegra/README.md
- meta-mender-toradex-nxp/README.md
Maintainers list as well as the responsibilities will now lives in the wiki.
https://github.com/mendersoftware/meta-mender-community/wiki/Community-maintainers
[Zeus port](https://github.com/mendersoftware/meta-mender-community/pull/239)
[Warrior port](https://github.com/mendersoftware/meta-mender-community/pull/240)
FYI
I've manually run the sed script to remove it on every branch, had some cherry-pick conflicts which weren't worth the manual work.
> Remove maintainers from readme

- meta-mender-atmel/README.md
- meta-mender-beaglebone/README.md
- meta-mender-coral/README.md
- meta-mender-imx/README.md
- meta-mender-intel/README.md
- meta-mender-nxp/README.md
- meta-mender-odroid/README.md
- meta-mender-qemu/README.md
- meta-mender-raspberrypi/README.md
- meta-mender-sunxi/README.md
- meta-mender-tegra/README.md
- meta-mender-tn-imx-bsp/README.md
- meta-mender-toradex-nxp/README.md
- meta-mender-variscite/README.md
Maintainers list as well as the responsibilities will now lives in the wiki.
https://github.com/mendersoftware/meta-mender-community/wiki/Community-maintainers
> Remove maintainer from readme

- meta-mender-toradex-nxp/recipes-bsp/u-boot/u-boot-toradex-fw-utils_%.bbappend
Some configurations use this instead of the mender-auto-provided version
so make sure it is Mender-integrated.
> toradex: Add recipe for u-boot-toradex-fw-utils.

- meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass
- meta-mender-toradex-nxp/classes/mender-toradex.bbclass
When using a combination of multiconfig and bbmask to enable builds both
with and without Mender in a single build dir, the existing sanity checks
would run even if all the Mender layers were masked out since they happened
at part time.  Moving them into an event handler allows them to be run
only when building with the Mender multiconfig.
> mender-tezi: Move sanity checks into an event handler.

- meta-mender-intel/scripts/manifest-intel.xml
In the dunfell branch, these revisions should be pointing to dunfell, right?
> Upgrade intel manifest to dunfell.

- meta-mender-intel/README.md
In a few spots in the README, zeus was still called out.
Signed-off-by: Tim Orling <tim.orling@konsulko.com>
> meta-mender-intel: change README.md to dunfell

- README.md
- meta-mender-amlogic/README.md
- meta-mender-amlogic/classes/sdimg-meson.bbclass
- meta-mender-amlogic/conf/layer.conf
- meta-mender-amlogic/recipes-bsp/u-boot/u-boot-meson-gx/mender.cfg
- meta-mender-amlogic/recipes-bsp/u-boot/u-boot-meson-gx_%.bbappend
- meta-mender-amlogic/scripts/manifest-amlogic.xml
- meta-mender-amlogic/templates/bblayers.conf.sample
- meta-mender-amlogic/templates/local.conf.append
- scripts/setup-environment
This adds the integration with https://github.com/superna9999/meta-meson an OE/poky layer for Amlogic SoCs based on Upstream Linux & U-boot.
Signed-off-by: Neil Armstrong <narmstrong@baylibre.com>
> Add mender Amlogic integration

- meta-mender-atmel/scripts/manifest-atmel.xml
Changelog: There was a recent change to the repo configuration for metal atmel
and does not allows ssh connections, only https.
Signed-off-by: Jaime Arrocha <jarrocha.dev@gmail.com>
> Change repo sync manifest form ssh to https

- meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass
These two changes make a huge difference in some cases. I have an image that I am installing using Toradex Easy Installer on an apalis-im6. Before these changes, the install took about 30 min.  After this change it was about 6 min.
> Speed up installation

- meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass
Allow configuration of image.json "config_format" and "autoinstall"
properties.
Code taken from image_type_tezi.bbclass: It allows user to change these
settings via .conf file if required by using the following variables:
TEZI_AUTO_INSTALL changes "autoinstall"
TEZI_CONFIG_FORMAT changes "config_format"
Signed-off-by: Jorge Solla <jorgesolla@gmail.com>
> Allow configuration of TEZI image.json properties.

- meta-mender-tegra/classes/sanity-meta-mender-tegra.bbclass
- meta-mender-tegra/classes/tegra-mender-setup.bbclass
- meta-mender-tegra/conf/layer.conf
- meta-mender-tegra/recipes-bsp/tegra-binaries/redundant-boot-overrides_1.0.bb
- meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-redundant-boot_%.bbappend
- meta-mender-tegra/recipes-bsp/u-boot/libubootenv_%.bbappend
- meta-mender-tegra/recipes-core/initrdscripts/tegra-minimal-init_%.bbappend
- meta-mender-tegra/recipes-mender/mender-client/mender-client_%.bbappend
- meta-mender-tegra/recipes-mender/tegra-state-scripts/tegra-state-scripts_1.0.bb
This branch includes the following trivial changes:
- manually updates various tegra-related overrides to use BitBake's new syntax
- removes the sanity check
With these changes and those on the `master-next` branch for `meta-mender` provided by @TheYoctoJester, I have built a mender artifact for the TX2 devkit board and successfully updated a board running `dunfell` using that artifact.
I have not tried flashing fresh, but that has lower priority than being able to update our units in the field.  This is a substantial step in the right direction.
> kirkstone fixes for meta-mender-tegra

- meta-mender-amlogic/scripts/manifest-amlogic.xml
GitHub dropped support for the legacy git protocol,
use https instead.
Signed-off-by: Neil Armstrong <narmstrong@baylibre.com>
> [dunfell] Change repo sync manifest form git protocol to https

- meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass
Replace hard coded values mmcblk0 and mmcblk0boot0 with a
configuration depending on value MENDER_STORAGE_DEVICE for
generating image.json in TEZI images for Toradex devices.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
> image_type_mender_tezi.bbclass: MENDER_STORAGE_DEVICE

- meta-mender-toradex-nxp/recipes-bsp/u-boot-distro-boot/files/toradex-bsp-5.4.0/0001-Adapt-boot.cmd.in-to-Mender.patch
Fix the patch to affoid the following issues:
Applying patch 0001-Adapt-boot.cmd.in-to-Mender.patch
patching file boot.cmd.in
Hunk #3 FAILED at 41.
1 out of 3 hunks FAILED -- rejects in file boot.cmd.in
Patch 0001-Adapt-boot.cmd.in-to-Mender.patch does not apply (enforce with -f)
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
> 001-Adapt-boot.cmd.in-to-Mender.patch: Fix

- meta-mender-toradex-nxp/recipes-bsp/grub-mender-grubenv/files/verdin-imx8mp/01_console_bootargs_grub.cfg
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.4.0/verdin-imx8mp/0001-configs-toradex-board-specific-mender-integration.patch
Add Mender support for Toradex verdin-imx8mp. To build an image
follow the steps for verdin-imx8mm and add the following extra
configurations, for example in local.conf:
```
MENDER_BOOT_PART_SIZE_MB = "32"
OFFSET_SPL_PAYLOAD = ""
MENDER_IMAGE_BOOTLOADER_BOOTSECTOR_OFFSET="0"
MENDER_UBOOT_STORAGE_INTERFACE = "mmc"
MENDER_UBOOT_STORAGE_DEVICE = "2"
MENDER_STORAGE_DEVICE = "/dev/mmcblk2"
```
Tested with `TORADEX_BSP_VERSION = "toradex-bsp-5.4.0"` and
`MACHINE = "verdin-imx8mp"` for image tdx-reference-minimal-image.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
> meta-mender-toradex-nxp: Support verdin-imx8mp

- meta-mender-toradex-nxp/README.md
- meta-mender-toradex-nxp/recipes-bsp/u-boot-distro-boot/files/toradex-bsp-5.6.0/0001-Adapt-boot.cmd.in-to-Mender.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/verdin-imx8mp/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/templates/local.conf.append
Hi,
Unfortunately my previous commit for Toradex BSP 5.6 had some issues which are now fixed:
* Added `0001-configs-toradex-board-specific-mender-integration.patch` for `verdin-imx8mp` and `toradex-bsp-5.6.0`.
* Reverted `0001-Adapt-boot.cmd.in-to-Mender.patch` to the previous version which is actually correct for BSP 5.6.
* Added a link to https://hub.mender.io/t/toradex-verdin-imx8m-plus/5026
* Added configurations for machine verdin-imx8mp to the template `local.conf.append` in sub-layer `meta-mender-toradex-nxp`.
Best regards,
Leon
> Bug fixes and improvements for verdin-imx8mp and Toradex BSP 5.6

- meta-mender-toradex-nxp/recipes-bsp/u-boot-distro-boot/files/toradex-bsp-5.7.0
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.3.0/apalis-imx8/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.4.0/apalis-imx8/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.5.0/apalis-imx8/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/apalis-imx8/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.7.0
This is just a symlink to 5.6.0 files since they work with 5.7.0 as well.
> toradex: Add bsp 5.7.0 support.

- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/colibri-imx8x/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/templates/local.conf.append
Adds mender support for Toradex colibri imx8x board for Toradex BSP 5.7.0
> colibri-imx8x: board integration for Toradex BSP 5.7.0

- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/apalis-imx6/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/apalis-imx8/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/colibri-imx8x/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/verdin-imx8mm/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/verdin-imx8mp/0001-configs-toradex-board-specific-mender-integration.patch
- meta-mender-toradex-nxp/templates/local.conf.append
Make sure we use the mender_dtb_name variable consistently across all support Toradex platforms. This loses the ability to define it dynamically which is the default (sort of) for Toradex but is better inline with standard Mender/Yocto integrations.
> toradex: Use mender_dtb_name consistently.

- meta-mender-toradex-nxp/recipes-bsp/u-boot/files/toradex-bsp-5.6.0/apalis-imx6/0001-configs-toradex-board-specific-mender-integration.patch
Make sure that PREBOOT is enabled and used on the apalis-imx6 board.  We use that to set fdtfile to mender_dtb_name.
> apalis-imx6: Properly enable PREBOOT for mender_dtb_name handling.

- meta-mender-nxp/recipes-bsp/u-boot/u-boot-mender-nxp.inc
Found some leftover unconverted overrides, which would effectively not apply the u-boot integration.
Ticket: None
> fix: override syntax in meta-mender-nxp

- meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/imx7d-pico/0001-ARM-Pico-Pi-i.MX7D-support-to-mender.patch
- meta-mender-nxp/templates/local.conf.append
Also add MENDER_STORAGE_TOTAL_SIZE_MB to 2048 to fix the following issue:
$: bmaptool copy core-image-base-imx7d-pico.sdimg /dev/sda bmaptool: info: discovered bmap file 'core-image-base-imx7d-pico.sdimg.bmap' bmaptool: ERROR: An error occurred, here is the traceback: Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 456, in copy_command
writer = BmapCopy.BmapBdevCopy(image_obj, dest_obj, bmap_obj,
File "/usr/lib/python3/dist-packages/bmaptools/BmapCopy.py", line 688, in __init__
raise Error("the image file '%s' has size %s and it will not "
bmaptool: ERROR: the image file 'core-image-base-imx7d-pico.sdimg' has size 4.0 GiB and it will not fit the block device '/dev/sda' which has 3.6 GiB capacity
Signed-off-by: Pierre-Jean Texier …
> meta-mender-nxp: imx7d-pico: rebase patch on kirkstone

- meta-mender-beaglebone/recipes-bsp/u-boot/u-boot_%.bbappend
For mender-uboot based integrations on the Beaglebone, we need to specify rootwait for the kirkstone branch. Timeouts were seen where the root filesystem was not available.
> beaglebone: Use rootwait when running with mender-uboot.

- meta-mender-toradex-nxp/classes/mender-toradex.bbclass
- meta-mender-toradex-nxp/recipes-bsp/u-boot-distro-boot/files/toradex-bsp-5.6.0/0001-Adapt-boot.cmd.in-to-Mender.patch
- meta-mender-toradex-nxp/templates/local.conf.append
These files should be loaded from the rootfs partition so we can update them OTA.
> RFC toradex: Move dtb and dtbo files to root partition.

- meta-mender-toradex-nxp/classes/mender-toradex.bbclass
- meta-mender-toradex-nxp/recipes-bsp/u-boot-distro-boot/files/toradex-bsp-6.0.0/0001-Adapt-boot.cmd.in-to-Mender.patch
- meta-mender-toradex-nxp/templates/local.conf.append
These patches bring the Toradex support in kirkstone up to feature-parity with dunfell.
> Kirkstone updates

- meta-mender-raspberrypi/templates/local.conf.append
> meta-mender-raspberrypi: fix :remove operator syntax in local.conf

- meta-mender-raspberrypi/templates/local.conf.append
Since kirkstone, the olde default boot patition size of 40MByte is not sufficient anymore for the Raspberry Pi 3.
Ticket: None
> meta-mender-raspberrypi: extend boot partition to 64MByte

- meta-mender-nxp/recipes-bsp/u-boot-scr/files/cubox-i/boot.cmd
- meta-mender-nxp/recipes-bsp/u-boot-scr/u-boot-scr.bb
- meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/cubox-i/0001-configs-mx6cuboxi_defconfig-Enable-Mender.patch
- meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc_%.bbappend
- meta-mender-nxp/recipes-bsp/u-boot/u-boot-mender-nxp.inc
- meta-mender-nxp/templates/local.conf.append
These patches add Mender support for SolidRun HummingBoard and Cubox-i (Yocto/OE BSP machine name is `cubox-i`. To build an image follow the generic steps for nxp and add the following extra configuration, for example in `local.conf` to accept EULA:
```
ACCEPT_FSL_EULA = "1"
```
I will add details about cubox-i to hub.mender.io.
Best regards,
Leon
> meta-mender-nxp: Support cubox-i and HummingBoard

- meta-mender-octavo-osd32mp/recipes-bsp/trusted-firmware-a/tf-a-stm32mp/0001-add-osd32mp1-red.patch
- meta-mender-octavo-osd32mp/recipes-kernel/linux/linux-stm32mp/0001-add-osd32mp1-red.patch
Unfortunately I missed an important feature in the osd32mp1 integration: the ethernet port is not enabled (the original work used only wifi).
Please consider this PR to fix that issue and enable board connectivity using ethernet.
With this fix the board becomes able to connect to the internet and run OTA updates from hosted.mender.io
Thanks,
António
> enable ethernet interface on osd32mp1-red

- meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc/patches/0003-Integration-of-Mender-boot-code-into-U-Boot.patch
- meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc_%.bbappend
When using u-boot-fslc 0003-Integration-of-Mender-boot-code-into-U-Boot.patch from meta-mender-core does not apply cleanly and throws a warning [patch-fuzz].
This is u-boot-fslc specific issue because u-boot-fslc does not use the kirkstone version of u-boot.
u-boot-fslc uses v2022.10 while kirkstone uses u-boot v2022.01.
> u-boot-fslc_%.bbappend: Overriding mender boot code integration patch

- meta-mender-nxp/recipes-bsp/u-boot/u-boot-fslc_%.bbappend
The `FILESEXTRAPATHS:prepend` in `u-boot-fslc_%.bbappend` has to be parsed after the modifications in `recipes-bsp/u-boot/u-boot-mender.inc` to let the u-boot-fslc specific patch have higher priority than the default one.
This fixes a minor mistake in my previous pull request #324
> u-boot-fslc_%.bbappend: Fix mender integration patch override priority

- meta-mender-intel/scripts/manifest-intel.xml
Tested on Seeed Studio Odyssey Blue and MeLe Quieter2Q. (Both platforms using Intel Celeron J4125)
> meta-mender-intel: use kirkstone branch instead of dunfell

- meta-mender-nxp/README.md
Add SolidRun HummingBoard i.MX6 SBC which is similar to SolidRun Cubox-i and both share the same machine name from Yocto/OE BSP layer meta-freescale-3rdparty.
> meta-mender-nxp/README.md: Add HummingBoard

- meta-mender-st-stm32mp/classes/stm32mp-gptimg.bbclass
This change removes git merge artifacts that are incompatible with bitbake
> Remove stm32mp merge artifacts

- meta-mender-ti/README.md
- meta-mender-ti/scripts/manifest-ti.xml
- meta-mender-ti/templates/bblayers.conf.sample
- meta-mender-ti/templates/local.conf.append
- scripts/setup-environment
This adds initial support for boards maintained in meta-ti. The first board integration is the BeaglePlay platform.
> meta-mender-ti: add initial support

- meta-mender-nxp/README.md
The board integration has already been merged, add the missing entry and link to Mender Hub post.
Ticket: None
> meta-mender-nxp: add imx8mq-voipac to README

- meta-mender-toradex-nxp/classes/image_type_mender_tezi.bbclass
Those files are deployed under ${DEPLOYDIR}/mender-tezi-metadata/ directory. Update their path to generate an image-*.json working out of the box.
> meta-mender-toradex-nxp: fix marketing and data location

- README.md
The build setups for board integrations are being moved from the Google repo tool to the kas tool, which is a solutions specifically tailored to the requirements of Yocto-based builds.
This adds instructions to both use and submit kas-based build configurations, as well as documents the repo deprecation.
Ticket: None
> feat: document kas configuration usage and submissions

- kas/raspberrypi4-64.yml
The machine type was a copy error from the
raspberrypi4.yml file.
Ticket: None
> fix: kas: machine type for raspberrypi4-64

- meta-mender-client-only/LICENSE
- meta-mender-client-only/README
- meta-mender-client-only/conf/layer.conf
- meta-mender-client-only/recipes-mender/mender-client/mender-client_%.bbappend
The meta-mender-client-only layer enables the Mender client to be installed and operated without the full integration in place.
Ticket: None
> client-only: add layer

- .github/workflows/build.yml
- kas/x86-virtual.yml
The x86-virtual machine shows how to build a vmdk image which can be booted on desktop virtualizations such as VirtualBox.
Ticket: None
> feat: kas: add x86-virtual machine

- meta-mender-nxp/recipes-bsp/u-boot/u-boot-boundary/0003-nitrogen8m-add-Mender-support.patch
Remove 3g_defconfig patch as defconfig no longer exists.
> u-boot-boundary: update nitrogen8m Mender support

- meta-mender-tegra/recipes-mender/mender-client/mender_%.bbappend
With Mender 4, the recipe name changed from `mender-client` to `mender` so a corresponding `mender_%.bbappend` is required.
> tegra: add bbappend for mender 4
